[package]
name = "ponde"
version = "0.1.5"
edition = "2021"
license = "MIT"
description = "Pointing device configurationd daemon for Wayland and X11 using libinput and uinput."
repository = "https://github.com/buzztaiki/ponde"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.14", features = ["derive", "deprecated"] }
evdev = "0.11.4"
input = "0.7.1"
libc = "0.2.126"
nix = "0.24.2"
serde = { version = "1.0.139", features = ["derive"] }
serde_yaml = "0.8.26"
thiserror = "1.0.31"

[dev-dependencies]
serde_test = "1.0.144"
